workload = {
	0: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'C': 3, 'K': 64, 'FY': 7, 'FX': 7, 'OY': 112, 'OX': 112},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': []},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 32), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 64), 'D2': ('FX', 4), 'D3': ('FY', 4)},
		'data_flow_d': {'D1': ('C', 3), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 64), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 112), 'D2': ('FX', 6), 'D3': ('FY', 6)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	1: {
		'equation': 'O[g][oy][ox]+=W[fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'G': 64, 'FY': 3, 'FX': 3, 'OY': 56, 'OX': 56},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 0},
		'operand_source': {'W': [], 'I': [0]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('G', 32)},
		'data_flow_a': {'D2': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 32)},
		'data_flow_c': {'D1': ('OX', 56), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D2': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 56)},
		'data_flow_f': {'D1': ('OX', 56), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	2: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 64, 'K': 64, 'FY': 3, 'FX': 3, 'OY': 56, 'OX': 56},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [1]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 32), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 56), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 56), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 56), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	3: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 64, 'K': 64, 'FY': 3, 'FX': 3, 'OY': 56, 'OX': 56},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [1, 2]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 32), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 56), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 56), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 56), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	4: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 64, 'K': 64, 'FY': 3, 'FX': 3, 'OY': 56, 'OX': 56},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [3]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 32), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 56), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 56), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 56), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	5: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 64, 'K': 64, 'FY': 3, 'FX': 3, 'OY': 56, 'OX': 56},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [3, 4]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 32), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 56), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 56), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 56), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	6: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'C': 64, 'K': 128, 'FY': 3, 'FX': 3, 'OY': 28, 'OX': 28},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [5]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 28), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 28), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 28), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 28), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	7: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'C': 64, 'K': 128, 'FY': 1, 'FX': 1, 'OY': 28, 'OX': 28},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [5]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 28), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 28)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 28), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 28), 'D2': ('FX', 1), 'D3': ('FY', 1)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 1), 'D3': ('FY', 1)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	8: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 128, 'K': 128, 'FY': 3, 'FX': 3, 'OY': 28, 'OX': 28},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [6, 7]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 28), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 28), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 28), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 28), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	9: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 128, 'K': 128, 'FY': 3, 'FX': 3, 'OY': 28, 'OX': 28},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [8]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 28), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 28), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 28), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 28), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	10: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 128, 'K': 128, 'FY': 3, 'FX': 3, 'OY': 28, 'OX': 28},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [8, 9]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 28), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 28), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 28), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 28), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	11: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'C': 128, 'K': 256, 'FY': 3, 'FX': 3, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [10]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	12: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'C': 128, 'K': 256, 'FY': 1, 'FX': 1, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [10]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14), 'D2': ('FX', 1), 'D3': ('FY', 1)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 1), 'D3': ('FY', 1)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	13: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 256, 'K': 256, 'FY': 3, 'FX': 3, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [11, 12]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	14: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 256, 'K': 256, 'FY': 3, 'FX': 3, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [13]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	15: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 256, 'K': 256, 'FY': 3, 'FX': 3, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [14, 13]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	16: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'C': 256, 'K': 512, 'FY': 3, 'FX': 3, 'OY': 7, 'OX': 7},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [15]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 7), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 7), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	17: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'C': 256, 'K': 512, 'FY': 1, 'FX': 1, 'OY': 7, 'OX': 7},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [15]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 7), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 7)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 7), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 7), 'D2': ('FX', 1), 'D3': ('FY', 1)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 1), 'D3': ('FY', 1)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	18: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 512, 'K': 512, 'FY': 3, 'FX': 3, 'OY': 7, 'OX': 7},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [16, 17]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 7), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 7), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	19: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 512, 'K': 512, 'FY': 3, 'FX': 3, 'OY': 7, 'OX': 7},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [18]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 7), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 7), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	20: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 512, 'K': 512, 'FY': 3, 'FX': 3, 'OY': 7, 'OX': 7},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [19, 18]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 7), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 7), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	######################### MOBILENET V2 STARTS HERE ###########################
	21: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'C': 3, 'K': 32, 'FY': 3, 'FX': 3, 'OY': 112, 'OX': 112},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': []},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 32), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 64), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_e': {'D1': ('OX', 64), 'D2': ('K', 32)},
		'data_flow_f': {'D1': ('OX', 112), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	22: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=ox+fx-1', 'iy=oy+fy-1'],
		'loop_dim_size': {'G': 32, 'FY': 3, 'FX': 3, 'OY': 112, 'OX': 112},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [21]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 32)},
		'data_flow_c': {'D1': ('OX', 64), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 64)},
		'data_flow_f': {'D1': ('OX', 112), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	23: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 32, 'K': 16, 'OY': 112, 'OX': 112},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [22]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 16)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 16)},
		'data_flow_b': {'D1': ('OX', 32), 'D2': ('K', 16)},
		'data_flow_c': {'D1': ('OX', 64)},
		'data_flow_d': {'D1': ('C', 32), 'D2': ('K', 16)},
		'data_flow_e': {'D1': ('OX', 64), 'D2': ('K', 16)},
		'data_flow_f': {'D1': ('OX', 112)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	24: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 16, 'K': 96, 'OY': 112, 'OX': 112},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [23]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 16), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 16), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 32), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 64)},
		'data_flow_d': {'D1': ('C', 16), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 64), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 112)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	25: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'G': 96, 'FY': 3, 'FX': 3, 'OY': 56, 'OX': 56},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [24]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 32)},
		'data_flow_c': {'D1': ('OX', 56), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 56)},
		'data_flow_f': {'D1': ('OX', 56), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	26: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 96, 'K': 24, 'OY': 56, 'OX': 56},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [25]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 24)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 24)},
		'data_flow_b': {'D1': ('OX', 32), 'D2': ('K', 24)},
		'data_flow_c': {'D1': ('OX', 56)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 24)},
		'data_flow_e': {'D1': ('OX', 56), 'D2': ('K', 24)},
		'data_flow_f': {'D1': ('OX', 56)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	27: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 24, 'K': 144, 'OY': 56, 'OX': 56},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [26]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 24), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 32), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 56)},
		'data_flow_d': {'D1': ('C', 24), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 56), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 56)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	28: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=ox+fx-1', 'iy=oy+fy-1'],
		'loop_dim_size': {'G': 144, 'FY': 3, 'FX': 3, 'OY': 56, 'OX': 56},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [27]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 32)},
		'data_flow_c': {'D1': ('OX', 56), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 56)},
		'data_flow_f': {'D1': ('OX', 56), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	29: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 144, 'K': 24, 'OY': 56, 'OX': 56},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [28]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 24)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 24)},
		'data_flow_b': {'D1': ('OX', 32), 'D2': ('K', 24)},
		'data_flow_c': {'D1': ('OX', 56)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 24)},
		'data_flow_e': {'D1': ('OX', 56), 'D2': ('K', 24)},
		'data_flow_f': {'D1': ('OX', 56)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	30: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 24, 'K': 144, 'OY': 56, 'OX': 56},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [26, 29]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 24), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 24), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 32), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 56)},
		'data_flow_d': {'D1': ('C', 24), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 56), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 56)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	31: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'G': 144, 'FY': 3, 'FX': 3, 'OY': 28, 'OX': 28},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [30]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 28)},
		'data_flow_c': {'D1': ('OX', 28), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 28)},
		'data_flow_f': {'D1': ('OX', 28), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	32: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 144, 'K': 32, 'OY': 28, 'OX': 28},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [31]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 28), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 28)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 32)},
		'data_flow_e': {'D1': ('OX', 28), 'D2': ('K', 32)},
		'data_flow_f': {'D1': ('OX', 28)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	33: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 32, 'K': 192, 'OY': 28, 'OX': 28},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [32]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 28), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 28)},
		'data_flow_d': {'D1': ('C', 32), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 28), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 28)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	34: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=ox+fx-1', 'iy=oy+fy-1'],
		'loop_dim_size': {'G': 192, 'FY': 3, 'FX': 3, 'OY': 28, 'OX': 28},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [33]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 28)},
		'data_flow_c': {'D1': ('OX', 28), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 28)},
		'data_flow_f': {'D1': ('OX', 28), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	35: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 192, 'K': 32, 'OY': 28, 'OX': 28},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [34]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 28), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 28)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 32)},
		'data_flow_e': {'D1': ('OX', 28), 'D2': ('K', 32)},
		'data_flow_f': {'D1': ('OX', 28)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	36: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 32, 'K': 192, 'OY': 28, 'OX': 28},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [32, 35]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 28), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 28)},
		'data_flow_d': {'D1': ('C', 32), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 28), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 28)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	37: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=ox+fx-1', 'iy=oy+fy-1'],
		'loop_dim_size': {'G': 192, 'FY': 3, 'FX': 3, 'OY': 28, 'OX': 28},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [36]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 28)},
		'data_flow_c': {'D1': ('OX', 28), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 28)},
		'data_flow_f': {'D1': ('OX', 28), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	38: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 192, 'K': 32, 'OY': 28, 'OX': 28},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [37]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 28), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 28)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 32)},
		'data_flow_e': {'D1': ('OX', 28), 'D2': ('K', 32)},
		'data_flow_f': {'D1': ('OX', 28)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	39: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 32, 'K': 192, 'OY': 28, 'OX': 28},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [35, 38]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 28), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 28)},
		'data_flow_d': {'D1': ('C', 32), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 28), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 28)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	40: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'FY': 3, 'FX': 3, 'G': 192, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [39]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 14)},
		'data_flow_c': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 14)},
		'data_flow_f': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	41: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 192, 'K': 64, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [40]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	42: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 64, 'K': 384, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [41]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	43: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=ox+fx-1', 'iy=oy+fy-1'],
		'loop_dim_size': {'G': 384, 'FY': 3, 'FX': 3, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [42]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 14)},
		'data_flow_c': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 14)},
		'data_flow_f': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	44: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 384, 'K': 64, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [43]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	45: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 64, 'K': 384, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [41, 44]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	46: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=ox+fx-1', 'iy=oy+fy-1'],
		'loop_dim_size': {'G': 384, 'FY': 3, 'FX': 3, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [45]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 14)},
		'data_flow_c': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 14)},
		'data_flow_f': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	47: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 384, 'K': 64, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [46]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	48: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 64, 'K': 384, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [44, 47]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	49: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=ox+fx-1', 'iy=oy+fy-1'],
		'loop_dim_size': {'G': 384, 'FY': 3, 'FX': 3, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [48]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 14)},
		'data_flow_c': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 14)},
		'data_flow_f': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	50: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 384, 'K': 64, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [49]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	51: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 64, 'K': 384, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [47, 50]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	52: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=ox+fx-1', 'iy=oy+fy-1'],
		'loop_dim_size': {'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3, 'G': 384},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [51]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 14)},
		'data_flow_c': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 14)},
		'data_flow_f': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	53: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 384, 'K': 96, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [52]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	54: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 96, 'K': 576, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [53]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	55: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=ox+fx-1', 'iy=oy+fy-1'],
		'loop_dim_size': {'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3, 'G': 576},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [54]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 14)},
		'data_flow_c': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 14)},
		'data_flow_f': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	56: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 576, 'K': 96, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [55]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	57: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 96, 'K': 576, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [53, 56]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	58: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=ox+fx-1', 'iy=oy+fy-1'],
		'loop_dim_size': {'OY': 14, 'OX': 14, 'FY': 3, 'FX': 3, 'G': 576},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [57]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 14)},
		'data_flow_c': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 14)},
		'data_flow_f': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	59: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 576, 'K': 96, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [58]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	60: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 96, 'K': 576, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [56, 59]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	61: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'loop_dim_size': {'OY': 7, 'OX': 7, 'FY': 3, 'FX': 3, 'G': 576},
		'stride': {'SY': 2, 'SX': 2},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [60]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 7)},
		'data_flow_c': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 7)},
		'data_flow_f': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	62: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 576, 'K': 160, 'OY': 7, 'OX': 7},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [61]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 7), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 7)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 7), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 7)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	63: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 160, 'K': 960, 'OY': 7, 'OX': 7},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [62]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 7), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 7)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 7), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 7)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	64: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=ox+fx-1', 'iy=oy+fy-1'],
		'loop_dim_size': {'OY': 7, 'OX': 7, 'FY': 3, 'FX': 3, 'G': 960},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [63]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 7)},
		'data_flow_c': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 7)},
		'data_flow_f': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	65: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 960, 'K': 160, 'OY': 7, 'OX': 7},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [64]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 7), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 7)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 7), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 7)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	66: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 160, 'K': 960, 'OY': 7, 'OX': 7},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [62, 65]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 7), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 7)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 7), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 7)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	67: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=ox+fx-1', 'iy=oy+fy-1'],
		'loop_dim_size': {'OY': 7, 'OX': 7, 'FY': 3, 'FX': 3, 'G': 960},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [66]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 7)},
		'data_flow_c': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 7)},
		'data_flow_f': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	68: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 960, 'K': 160, 'OY': 7, 'OX': 7},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [67]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 7), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 7)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 7), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 7)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	69: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 160, 'K': 960, 'OY': 7, 'OX': 7},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [65, 68]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 7), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 7)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 7), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 7)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	70: {
		'equation': 'O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=ox+fx-1', 'iy=oy+fy-1'],
		'loop_dim_size': {'OY': 7, 'OX': 7, 'FY': 3, 'FX': 3, 'G': 960},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [69]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('G', 32)},
		'data_flow_a': {'D1': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 7)},
		'data_flow_c': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 7)},
		'data_flow_f': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	71: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 960, 'K': 320, 'OY': 7, 'OX': 7},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [70]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 7), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 7)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 7), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 7)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	72: {
		'equation': 'O[k][oy][ox]+=W[k][c]*I[c][ox][oy]',
		'equation_relations': [],
		'loop_dim_size': {'C': 320, 'K': 1280, 'OY': 7, 'OX': 7},
		'operand_precision': {'O': 16, 'O_final': 8, 'W': 8, 'I': 8},
		'operand_source': {'W': [], 'I': [71]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 7), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 7)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 7), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 7)},
		'data_flow_g': {'D1': ('OX', 4)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	######################### Tiny YOLO starty here ###########################
	73: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 3, 'K': 16, 'FY': 3, 'FX': 3, 'OY': 448, 'OX': 448},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': []},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 3), 'D2': ('K', 16)},
		'data_flow_b': {'D1': ('OX', 32), 'D2': ('K', 16)},
		'data_flow_c': {'D1': ('OX', 64), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 3), 'D2': ('K', 16)},
		'data_flow_e': {'D1': ('OX', 64), 'D2': ('K', 16)},
		'data_flow_f': {'D1': ('OX', 112), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	74: {
		'equation': 'O[g][oy][ox]+=W[fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'G': 16, 'FY': 2, 'FX': 2, 'OY': 224, 'OX': 224},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 0},
		'operand_source': {'W': [], 'I': [73]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('G', 32)},
		'data_flow_a': {'D2': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 32)},
		'data_flow_c': {'D1': ('OX', 64), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'data_flow_d': {'D2': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 64)},
		'data_flow_f': {'D1': ('OX', 112), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	75: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 16, 'K': 32, 'FY': 3, 'FX': 3, 'OY': 224, 'OX': 224},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [74]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 16), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 32), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 64), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 16), 'D2': ('K', 32)},
		'data_flow_e': {'D1': ('OX', 64), 'D2': ('K', 32)},
		'data_flow_f': {'D1': ('OX', 112), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	76: {
		'equation': 'O[g][oy][ox]+=W[fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'G': 32, 'FY': 2, 'FX': 2, 'OY': 112, 'OX': 112},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 0},
		'operand_source': {'W': [], 'I': [75]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('G', 32)},
		'data_flow_a': {'D2': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 32)},
		'data_flow_c': {'D1': ('OX', 64), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'data_flow_d': {'D2': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 64)},
		'data_flow_f': {'D1': ('OX', 112), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	77: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 32, 'K': 64, 'FY': 3, 'FX': 3, 'OY': 112, 'OX': 112},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [76]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 32), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 64), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 32), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 64), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 112), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	78: {
		'equation': 'O[g][oy][ox]+=W[fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'G': 64, 'FY': 2, 'FX': 2, 'OY': 56, 'OX': 56},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 0},
		'operand_source': {'W': [], 'I': [77]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('G', 32)},
		'data_flow_a': {'D2': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 32)},
		'data_flow_c': {'D1': ('OX', 56), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'data_flow_d': {'D2': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 56)},
		'data_flow_f': {'D1': ('OX', 56), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	79: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 64, 'K': 128, 'FY': 3, 'FX': 3, 'OY': 56, 'OX': 56},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [78]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 32), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 56), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 56), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 56), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	80: {
		'equation': 'O[g][oy][ox]+=W[fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'G': 128, 'FY': 2, 'FX': 2, 'OY': 28, 'OX': 28},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 0},
		'operand_source': {'W': [], 'I': [79]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('G', 32)},
		'data_flow_a': {'D2': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 28)},
		'data_flow_c': {'D1': ('OX', 28), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'data_flow_d': {'D2': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 28)},
		'data_flow_f': {'D1': ('OX', 28), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	81: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 128, 'K': 256, 'FY': 3, 'FX': 3, 'OY': 28, 'OX': 28},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [80]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 28), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 28), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 28), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 28), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	82: {
		'equation': 'O[g][oy][ox]+=W[fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'G': 256, 'FY': 2, 'FX': 2, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 0},
		'operand_source': {'W': [], 'I': [81]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('G', 32)},
		'data_flow_a': {'D2': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 14)},
		'data_flow_c': {'D1': ('OX', 14), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'data_flow_d': {'D2': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 14)},
		'data_flow_f': {'D1': ('OX', 14), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	83: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 256, 'K': 512, 'FY': 3, 'FX': 3, 'OY': 14, 'OX': 14},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [82]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 14), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 14), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 14), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	84: {
		'equation': 'O[g][oy][ox]+=W[fy][fx]*I[g][ix][iy]',
		'equation_relations': ['ix=2*ox+1*fx', 'iy=2*oy+1*fy'],
		'stride': {'SY': 2, 'SX': 2},
		'loop_dim_size': {'G': 512, 'FY': 2, 'FX': 2, 'OY': 7, 'OX': 7},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 0},
		'operand_source': {'W': [], 'I': [83]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('G', 32)},
		'data_flow_a': {'D2': ('G', 1)},
		'data_flow_b': {'D1': ('OX', 7)},
		'data_flow_c': {'D1': ('OX', 7), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'data_flow_d': {'D2': ('G', 1)},
		'data_flow_e': {'D1': ('OX', 7)},
		'data_flow_f': {'D1': ('OX', 7), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 2), 'D3': ('FY', 2)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	85: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 512, 'K': 1024, 'FY': 3, 'FX': 3, 'OY': 7, 'OX': 7},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [84]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 7), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 7), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
	86: {
		'equation': 'O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]',
		'equation_relations': ['ix=1*ox+1*fx', 'iy=1*oy+1*fy'],
		'loop_dim_size': {'C': 1024, 'K': 256, 'FY': 3, 'FX': 3, 'OY': 7, 'OX': 7},
		'operand_precision': {'O': 16, 'O_final': 8, 'I': 8, 'W': 8},
		'operand_source': {'W': [], 'I': [85]},
		'core_allocation': 1,
		'spatial_mapping': {'D1': ('C', 3), 'D2': ('K', 32)},
		'data_flow_a': {'D1': ('C', 32), 'D2': ('K', 32)},
		'data_flow_b': {'D1': ('OX', 7), 'D2': ('K', 32)},
		'data_flow_c': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_d': {'D1': ('C', 64), 'D2': ('K', 64)},
		'data_flow_e': {'D1': ('OX', 7), 'D2': ('K', 64)},
		'data_flow_f': {'D1': ('OX', 7), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'data_flow_g': {'D1': ('OX', 4), 'D2': ('FX', 3), 'D3': ('FY', 3)},
		'memory_operand_links': {'O': 'O', 'W': 'I2', 'I': 'I1'}
	}
	,
}