workload = {
    0: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"C": 3, "K": 64, "FY": 7, "FX": 7, "OY": 112, "OX": 112},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": []},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "padding": {"IY": (3, 3), "IX": (3, 3)},
    },
    1: {
        "operator_type": "MaxPool",
        "equation": "O[g][oy][ox]+=W[fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"G": 64, "FY": 3, "FX": 3, "OY": 56, "OX": 56},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 0},
        "operand_source": {"W": [], "I": [0]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    2: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 64, "K": 64, "FY": 3, "FX": 3, "OY": 56, "OX": 56},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [1]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    3: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 64, "K": 64, "FY": 3, "FX": 3, "OY": 56, "OX": 56},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [1, 2]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    4: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 64, "K": 64, "FY": 3, "FX": 3, "OY": 56, "OX": 56},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [3]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    5: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 64, "K": 64, "FY": 3, "FX": 3, "OY": 56, "OX": 56},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [3, 4]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    6: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"C": 64, "K": 128, "FY": 3, "FX": 3, "OY": 28, "OX": 28},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [5]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    7: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"C": 64, "K": 128, "FY": 1, "FX": 1, "OY": 28, "OX": 28},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [5]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    8: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 128, "K": 128, "FY": 3, "FX": 3, "OY": 28, "OX": 28},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [6, 7]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    9: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 128, "K": 128, "FY": 3, "FX": 3, "OY": 28, "OX": 28},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [8]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    10: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 128, "K": 128, "FY": 3, "FX": 3, "OY": 28, "OX": 28},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [8, 9]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    11: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"C": 128, "K": 256, "FY": 3, "FX": 3, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [10]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    12: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"C": 128, "K": 256, "FY": 1, "FX": 1, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [10]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    13: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 256, "K": 256, "FY": 3, "FX": 3, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [11, 12]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    14: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 256, "K": 256, "FY": 3, "FX": 3, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [13]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    15: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 256, "K": 256, "FY": 3, "FX": 3, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [14, 13]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    16: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"C": 256, "K": 512, "FY": 3, "FX": 3, "OY": 7, "OX": 7},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [15]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    17: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"C": 256, "K": 512, "FY": 1, "FX": 1, "OY": 7, "OX": 7},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [15]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    18: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 512, "K": 512, "FY": 3, "FX": 3, "OY": 7, "OX": 7},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [16, 17]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    19: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 512, "K": 512, "FY": 3, "FX": 3, "OY": 7, "OX": 7},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [18]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    20: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 512, "K": 512, "FY": 3, "FX": 3, "OY": 7, "OX": 7},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [19, 18]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    21: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"C": 3, "K": 32, "FY": 3, "FX": 3, "OY": 112, "OX": 112},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": []},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    22: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=ox+fx-1", "iy=oy+fy-1"],
        "loop_dim_size": {"G": 32, "FY": 3, "FX": 3, "OY": 112, "OX": 112},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [21]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    23: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 32, "K": 16, "OY": 112, "OX": 112},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [22]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    24: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 16, "K": 96, "OY": 112, "OX": 112},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [23]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    25: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"G": 96, "FY": 3, "FX": 3, "OY": 56, "OX": 56},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [24]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    26: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 96, "K": 24, "OY": 56, "OX": 56},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [25]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    27: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 24, "K": 144, "OY": 56, "OX": 56},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [26]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    28: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=ox+fx-1", "iy=oy+fy-1"],
        "loop_dim_size": {"G": 144, "FY": 3, "FX": 3, "OY": 56, "OX": 56},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [27]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    29: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 144, "K": 24, "OY": 56, "OX": 56},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [28]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    30: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 24, "K": 144, "OY": 56, "OX": 56},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [26, 29]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    31: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"G": 144, "FY": 3, "FX": 3, "OY": 28, "OX": 28},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [30]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    32: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 144, "K": 32, "OY": 28, "OX": 28},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [31]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    33: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 32, "K": 192, "OY": 28, "OX": 28},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [32]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    34: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=ox+fx-1", "iy=oy+fy-1"],
        "loop_dim_size": {"G": 192, "FY": 3, "FX": 3, "OY": 28, "OX": 28},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [33]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    35: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 192, "K": 32, "OY": 28, "OX": 28},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [34]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    36: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 32, "K": 192, "OY": 28, "OX": 28},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [32, 35]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    37: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=ox+fx-1", "iy=oy+fy-1"],
        "loop_dim_size": {"G": 192, "FY": 3, "FX": 3, "OY": 28, "OX": 28},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [36]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    38: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 192, "K": 32, "OY": 28, "OX": 28},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [37]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    39: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 32, "K": 192, "OY": 28, "OX": 28},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [35, 38]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    40: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"FY": 3, "FX": 3, "G": 192, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [39]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    41: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 192, "K": 64, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [40]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    42: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 64, "K": 384, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [41]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    43: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=ox+fx-1", "iy=oy+fy-1"],
        "loop_dim_size": {"G": 384, "FY": 3, "FX": 3, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [42]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    44: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 384, "K": 64, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [43]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    45: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 64, "K": 384, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [41, 44]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    46: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=ox+fx-1", "iy=oy+fy-1"],
        "loop_dim_size": {"G": 384, "FY": 3, "FX": 3, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [45]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    47: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 384, "K": 64, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [46]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    48: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 64, "K": 384, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [44, 47]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    49: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=ox+fx-1", "iy=oy+fy-1"],
        "loop_dim_size": {"G": 384, "FY": 3, "FX": 3, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [48]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    50: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 384, "K": 64, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [49]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    51: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 64, "K": 384, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [47, 50]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    52: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=ox+fx-1", "iy=oy+fy-1"],
        "loop_dim_size": {"OY": 14, "OX": 14, "FY": 3, "FX": 3, "G": 384},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [51]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    53: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 384, "K": 96, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [52]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    54: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 96, "K": 576, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [53]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    55: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=ox+fx-1", "iy=oy+fy-1"],
        "loop_dim_size": {"OY": 14, "OX": 14, "FY": 3, "FX": 3, "G": 576},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [54]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    56: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 576, "K": 96, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [55]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    57: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 96, "K": 576, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [53, 56]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    58: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=ox+fx-1", "iy=oy+fy-1"],
        "loop_dim_size": {"OY": 14, "OX": 14, "FY": 3, "FX": 3, "G": 576},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [57]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    59: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 576, "K": 96, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [58]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    60: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 96, "K": 576, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [56, 59]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    61: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"OY": 7, "OX": 7, "FY": 3, "FX": 3, "G": 576},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [60]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    62: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 576, "K": 160, "OY": 7, "OX": 7},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [61]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    63: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 160, "K": 960, "OY": 7, "OX": 7},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [62]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    64: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=ox+fx-1", "iy=oy+fy-1"],
        "loop_dim_size": {"OY": 7, "OX": 7, "FY": 3, "FX": 3, "G": 960},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [63]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    65: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 960, "K": 160, "OY": 7, "OX": 7},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [64]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    66: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 160, "K": 960, "OY": 7, "OX": 7},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [62, 65]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    67: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=ox+fx-1", "iy=oy+fy-1"],
        "loop_dim_size": {"OY": 7, "OX": 7, "FY": 3, "FX": 3, "G": 960},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [66]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    68: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 960, "K": 160, "OY": 7, "OX": 7},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [67]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    69: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 160, "K": 960, "OY": 7, "OX": 7},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [65, 68]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    70: {
        "operator_type": "Conv",
        "equation": "O[g][oy][ox]+=W[g][fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=ox+fx-1", "iy=oy+fy-1"],
        "loop_dim_size": {"OY": 7, "OX": 7, "FY": 3, "FX": 3, "G": 960},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [69]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    71: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 960, "K": 320, "OY": 7, "OX": 7},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [70]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    72: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c]*I[c][ox][oy]",
        "dimension_relations": [],
        "loop_dim_size": {"C": 320, "K": 1280, "OY": 7, "OX": 7},
        "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": [71]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    73: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 3, "K": 16, "FY": 3, "FX": 3, "OY": 448, "OX": 448},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": []},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    74: {
        "operator_type": "MaxPool",
        "equation": "O[g][oy][ox]+=W[fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"G": 16, "FY": 2, "FX": 2, "OY": 224, "OX": 224},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 0},
        "operand_source": {"W": [], "I": [73]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    75: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 16, "K": 32, "FY": 3, "FX": 3, "OY": 224, "OX": 224},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [74]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    76: {
        "operator_type": "MaxPool",
        "equation": "O[g][oy][ox]+=W[fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"G": 32, "FY": 2, "FX": 2, "OY": 112, "OX": 112},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 0},
        "operand_source": {"W": [], "I": [75]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    77: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 32, "K": 64, "FY": 3, "FX": 3, "OY": 112, "OX": 112},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [76]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    78: {
        "operator_type": "MaxPool",
        "equation": "O[g][oy][ox]+=W[fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"G": 64, "FY": 2, "FX": 2, "OY": 56, "OX": 56},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 0},
        "operand_source": {"W": [], "I": [77]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    79: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 64, "K": 128, "FY": 3, "FX": 3, "OY": 56, "OX": 56},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [78]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    80: {
        "operator_type": "MaxPool",
        "equation": "O[g][oy][ox]+=W[fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"G": 128, "FY": 2, "FX": 2, "OY": 28, "OX": 28},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 0},
        "operand_source": {"W": [], "I": [79]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    81: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 128, "K": 256, "FY": 3, "FX": 3, "OY": 28, "OX": 28},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [80]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    82: {
        "operator_type": "MaxPool",
        "equation": "O[g][oy][ox]+=W[fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"G": 256, "FY": 2, "FX": 2, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 0},
        "operand_source": {"W": [], "I": [81]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    83: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 256, "K": 512, "FY": 3, "FX": 3, "OY": 14, "OX": 14},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [82]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    84: {
        "operator_type": "MaxPool",
        "equation": "O[g][oy][ox]+=W[fy][fx]*I[g][ix][iy]",
        "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
        "loop_dim_size": {"G": 512, "FY": 2, "FX": 2, "OY": 7, "OX": 7},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 0},
        "operand_source": {"W": [], "I": [83]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    85: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 512, "K": 1024, "FY": 3, "FX": 3, "OY": 7, "OX": 7},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [84]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "G"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
    86: {
        "operator_type": "Conv",
        "equation": "O[k][oy][ox]+=W[k][c][fy][fx]*I[c][ix][iy]",
        "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
        "loop_dim_size": {"C": 1024, "K": 256, "FY": 3, "FX": 3, "OY": 7, "OX": 7},
        "operand_precision": {"O": 16, "O_final": 8, "I": 8, "W": 8},
        "operand_source": {"W": [], "I": [85]},
        "memory_operand_links": {"O": "O", "W": "I2", "I": "I1"},
        "constant_operands": ["W"],
        "operand_source_dimension_mapping": {"I": {"IX": "OX", "IY": "OY", "C": "K"}},
        "padding": {"IY": (0, 0), "IX": (0, 0)},
    },
}
